name: Workflow
on:
  push:
    branches:
      - feature-clase1

jobs: 
  SAST:
    runs-on: ubuntu-latest
    steps:

    - name: Set up JDK 17
      uses: action/setup-java@v4.5.0
      with:
        java-version: '17'
        distribution: 'adopt'

    - name: Checkout code
      uses: actions/checkout@v4.2.2

    - name: Build
      run: |
        chmod 777 gradlew
        ./gradlew build 
  
  


