name: Workflow
on:
  push:
    branches:
      - feature-clase1

jobs: 
  create-sonar-project:
    runs-on: ubuntu-latest
    steps:
      - name: Send request to SonarCloud API
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
          REPO_NAME: ${{ github.event.repository.name }}
        run: |
          curl -f -X POST -u "${SONAR_TOKEN}:" \
          "https://sonarcloud.io/api/projects/create" \
          -d "name=${REPO_NAME}" \
          -d "project=${REPO_NAME}" \
          -d "organization=devsecopsusach" \
          -d "visibility=public"