name: Workflow
on:
  push:
    branches:
      - feature-clase1

jobs: 
  SAST:
    runs-on: ubuntu-latest
    steps:

    - name: Creando Proyecto en Sonarcloud
      env:
        SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        REPO_NAME: ${{ github.event.repository.name }}
      run: |
        curl -f -X POST -u '${{ secrets.SONAR_TOKEN }}:' 'https://sonarcloud.io/api/projects/create' -d 'name=${REPO_NAME}' 'project=${REPO_NAME}' -d 'organization=devsecopsusach' -d 'visibility=public'
  