name: Workflow
on:
  push:
    branches:
      - feature-clase1

jobs: 
  SAST:
    runs-on: ubuntu-24.04
    steps:

    - name: Creando Proyecto en Sonarcloud
      run: |
        set +e
        curl -f -X POST -u '${{ secrets.SONAR_TOKEN }}:' 'https://sonarcloud.io/api/projects/create' -d 'name=pet-clinic' 'project=${{ github.event.repository.name }}' -d 'organization=devsecopsusach' -d 'visibility=public'
  