name: Workflow
on:
  push:
    branches:
      - feature-clase1

jobs: 
  SAST:
    runs-on: ubuntu-latest
    steps:

    - name: Creando Proyecto en Sonarcloud
      run: |
        curl -f -X POST -u '${{ secret.SONAR_TOKEN }}:' 'https://sonarcloud.io/api/projects/create' -d 'name=${{ github.event.repository.name }}' -d 'organization=devsecopsusach' -d 'visibility=public'
  
  


