name: Workflow
on:
  push:
    branches:
      - main

jobs: 
  BUILD:
    runs-on: ubuntu-latest
    steps:

      - name: Aqui compilamos
        run: | 
          echo 'Aqui compilamos'
    
  TESTING:
    runs-on: ubuntu-latest
    steps:

      - name: TESTING
        run: | 
          echo 'TESTING'

  
  
  


